---
# Base configuration.
homeassistant:
  name: nerdhaus
  latitude: !secret home_latititude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: America/Toronto
  country: CA
  external_url: "https://hass.nerdhaus.ca"
  packages: !include_dir_named packages

automation: !include automations.yaml
automation manual: !include_dir_merge_list automations/
script: !include_dir_merge_named scripts/
scene: !include scenes.yaml

battery_notes:
