- alias: Keep office cool
  description: ""
  id: "7b7450b6-0811-4c44-9581-0461adcf912e"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_office_temperature
      above: "24"
  condition: []
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.air_conditioner

- alias: Turn off office AC
  description: ""
  id: "380dc2cc-c43b-4c69-bc36-6923b956f8be"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.home_office_temperature
      below: "22"
  condition: []
  action:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.air_conditioner
