- alias: Bedroom TV Time
  description: "Put the purifier in night mode when the TV starts playing"
  id: "331f421c-c0b6-41cf-98ce-2ab0126a335a"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - media_player.bedroom_2
      to: playing
  condition: []
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.purifier_humidify_cool_formaldehyde_night_mode

- alias: Bedroom TV Time Over
  description: ""
  id: "826af719-2a40-431f-8f02-4fa935369c3e"
  mode: single
  trigger:
    - platform: state
      entity_id:
        - media_player.bedroom_2
      to: standby
  condition: []
  action:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.purifier_humidify_cool_formaldehyde_night_mode
