# Example configuration.yaml entry
- alias: "Update Available Notification"
  trigger:
    - platform: state
      entity_id: binary_sensor.home_assistant_website_update_available
      from: "off"
      to: "on"
  action:
    - service: notify.notify
      data:
        message: "Home Assistant {{ states('sensor.home_assistant_website') }} is available."
