- alias: Turn on light rack
  description: ""
  id: "24dcac6e-5577-44a8-b3ea-9249a299c3f6"
  mode: single
  trigger:
    - platform: time
      at: 08:00:00
  condition: []
  action:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.light_rack

- alias: Turn off light rack
  description: ""
  id: "3939a056-c910-4b46-8437-06335b355350"
  mode: single
  trigger:
    - platform: time
      at: "22:00:00"
  condition: []
  action:
    - service: switch.turn_off
      data: {}
      target:
        entity_id: switch.light_rack
